package yumo.achat.core.model

/**
 * Core重构模型扩展登记表。
 *
 * 这个登记表把脚手架基线中的值模型逐项映射到当前生产源码，冻结已确认的
 * ach_ 前缀扩展字段。字段采用默认值策略，仅作为兼容审查与后续协议演进的
 * 元数据入口，不改变既有 data class 的 equals/hashCode/copy 或网络重试 key。
 */
public data class AchatModelExtensionDescriptor(
    val sourceId: String,
    val targetType: String,
    val fieldName: String,
    val serialName: String,
    val legacyDefault: String,
)

public object AchatCoreRefactorModelRegistry {
    public const val ACH_MODEL_TRACE_FIELD: String = "ach_modelTrace"
    public const val ACH_MODEL_TRACE_SERIAL_NAME: String = "ach_modelTrace"
    public const val ACH_MODEL_TRACE_LEGACY_DEFAULT: String = ""

    public val descriptors: List<AchatModelExtensionDescriptor> = listOf(
        AchatModelExtensionDescriptor(
            sourceId = "app/src/main/java/com/vexora/app/analytics/BusinessEventQueue.kt:13:BusinessEvent",
            targetType = "yumo.achat.core.model.BusinessEvent",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "app/src/main/java/com/vexora/app/ui/catalog/CatalogViewModel.kt:15:CatalogUiState",
            targetType = "yumo.achat.core.model.CatalogUiState",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "app/src/main/java/com/vexora/app/ui/generation/GenerationViewModel.kt:19:QualityOption",
            targetType = "yumo.achat.core.model.QualityOption",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "app/src/main/java/com/vexora/app/ui/generation/GenerationViewModel.kt:20:GenerationOptions",
            targetType = "yumo.achat.core.model.GenerationOptions",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "app/src/main/java/com/vexora/app/ui/generation/GenerationViewModel.kt:21:GenerationUiState",
            targetType = "yumo.achat.core.model.GenerationUiState",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "app/src/main/java/com/vexora/app/ui/generation/LibraryScreen.kt:29:ProfilePreview",
            targetType = "yumo.achat.core.model.ProfilePreview",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "app/src/main/java/com/vexora/app/ui/generation/UploadedPhotosViewModel.kt:15:UploadedPhotosState",
            targetType = "yumo.achat.core.model.UploadedPhotosState",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "app/src/main/java/com/vexora/app/ui/generation/VisualLibraryViewModel.kt:13:VisualLibraryState",
            targetType = "yumo.achat.core.model.VisualLibraryState",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "app/src/main/java/com/vexora/app/ui/login/AuthViewModel.kt:15:AuthUiState",
            targetType = "yumo.achat.core.model.AuthUiState",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "app/src/main/java/com/vexora/app/ui/login/RegionGateViewModel.kt:17:RegionGateState",
            targetType = "yumo.achat.core.model.RegionGateState",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "app/src/main/java/com/vexora/app/ui/settings/SettingsViewModel.kt:8:SettingsConfiguration",
            targetType = "yumo.achat.core.model.SettingsConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "app/src/main/java/com/vexora/app/ui/wallet/TransactionAmount.kt:9:TransactionAmount",
            targetType = "yumo.achat.core.model.TransactionAmount",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "app/src/main/java/com/vexora/app/ui/wallet/WalletViewModel.kt:14:WalletUiState",
            targetType = "yumo.achat.core.model.WalletUiState",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "app/src/main/java/com/vexora/app/ui/web/WebViewModel.kt:14:WebContent",
            targetType = "yumo.achat.core.model.WebContent",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/analytics/AnalyticsSink.kt:10:AnalyticsPolicy",
            targetType = "yumo.achat.core.analytics.AnalyticsPolicy",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/analytics/BackendAnalyticsSink.kt:28:PendingEvent",
            targetType = "yumo.achat.core.analytics.PendingEvent",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/analytics/EventApi.kt:17:ReportEventRequest",
            targetType = "yumo.achat.core.analytics.ReportEventRequest",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/analytics/EventTracker.kt:14:AnalyticsConfiguration",
            targetType = "yumo.achat.core.analytics.AnalyticsConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/attribution/AttributionModels.kt:10:LoginAttribution",
            targetType = "yumo.achat.core.attribution.LoginAttribution",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/attribution/AttributionModels.kt:26:Success",
            targetType = "yumo.achat.core.attribution.Success",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/attribution/AttributionModels.kt:42:AttributionConfiguration",
            targetType = "yumo.achat.core.attribution.AttributionConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/auth/AnonymousStartup.kt:10:StartupConfiguration",
            targetType = "yumo.achat.core.auth.StartupConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/auth/SessionCoordinator.kt:16:Session",
            targetType = "yumo.achat.core.auth.Session",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/auth/UserProfileRepository.kt:18:UserProfile",
            targetType = "yumo.achat.core.auth.UserProfile",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/auth/UserProfileRepository.kt:26:ProfileMode",
            targetType = "yumo.achat.core.auth.ProfileMode",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/billing/BillingConfiguration.kt:3:BillingConfiguration",
            targetType = "yumo.achat.core.billing.BillingConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/billing/BillingProduct.kt:3:BillingProduct",
            targetType = "yumo.achat.core.billing.BillingProduct",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/billing/BillingProduct.kt:16:SubscriptionOfferDetails",
            targetType = "yumo.achat.core.billing.SubscriptionOfferDetails",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/billing/BillingProduct.kt:23:PricingPhase",
            targetType = "yumo.achat.core.billing.PricingPhase",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/billing/BillingPurchase.kt:3:BillingPurchase",
            targetType = "yumo.achat.core.billing.BillingPurchase",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/billing/BillingPurchase.kt:28:BillingResult",
            targetType = "yumo.achat.core.billing.BillingResult",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/billing/CoinPurchaseController.kt:15:CoinPurchaseState",
            targetType = "yumo.achat.core.billing.CoinPurchaseState",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/billing/ConsumablePurchaseOrchestrator.kt:85:Success",
            targetType = "yumo.achat.core.billing.Success",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/billing/ConsumablePurchaseOrchestrator.kt:86:Pending",
            targetType = "yumo.achat.core.billing.Pending",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/billing/ConsumablePurchaseOrchestrator.kt:87:Failure",
            targetType = "yumo.achat.core.billing.Failure",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/billing/ConsumablePurchaseOrchestrator.kt:91:Success",
            targetType = "yumo.achat.core.billing.Success\$Variant2",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/billing/ConsumablePurchaseOrchestrator.kt:93:Failure",
            targetType = "yumo.achat.core.billing.Failure\$Variant2",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/billing/ConsumablePurchaseOrchestrator.kt:99:Pending",
            targetType = "yumo.achat.core.billing.Pending\$Variant2",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/billing/PendingPurchaseRegistry.kt:3:PendingPurchaseRecord",
            targetType = "yumo.achat.core.billing.PendingPurchaseRecord",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/catalog/ApiTemplateRepository.kt:9:CatalogConfiguration",
            targetType = "yumo.achat.core.catalog.CatalogConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/catalog/TemplateRepository.kt:12:TemplateCategory",
            targetType = "yumo.achat.core.catalog.TemplateCategory",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/catalog/TemplateRepository.kt:13:TemplateMedia",
            targetType = "yumo.achat.core.catalog.TemplateMedia",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/catalog/TemplateRepository.kt:30:TemplatePrices",
            targetType = "yumo.achat.core.catalog.TemplatePrices",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/catalog/TemplateRepository.kt:37:Template",
            targetType = "yumo.achat.core.catalog.Template",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/catalog/TemplateRepository.kt:44:TemplateCatalog",
            targetType = "yumo.achat.core.catalog.TemplateCatalog",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/catalog/TemplateRepository.kt:52:CatalogFixture",
            targetType = "yumo.achat.core.catalog.CatalogFixture",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/config/AppConfiguration.kt:5:AccountRules",
            targetType = "yumo.achat.core.config.AccountRules",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/config/AppConfiguration.kt:14:AppConfiguration",
            targetType = "yumo.achat.core.config.AppConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/config/ClientIdentity.kt:3:ClientIdentity",
            targetType = "yumo.achat.core.config.ClientIdentity",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/config/CoreRuntimeConfig.kt:8:CoreRuntimeConfig",
            targetType = "yumo.achat.core.config.CoreRuntimeConfig",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/config/CoreRuntimeConfig.kt:14:NetworkConfig",
            targetType = "yumo.achat.core.config.NetworkConfig",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/config/CoreRuntimeConfig.kt:51:StorageConfig",
            targetType = "yumo.achat.core.config.StorageConfig",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/config/CoreRuntimeConfig.kt:61:DiagnosticsConfig",
            targetType = "yumo.achat.core.config.DiagnosticsConfig",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/network/ApiModels.kt:11:ApiResponse",
            targetType = "yumo.achat.core.network.ApiResponse",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/network/ApiModels.kt:26:LoginRequest",
            targetType = "yumo.achat.core.network.LoginRequest",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/network/ApiModels.kt:30:AnonymousRequest",
            targetType = "yumo.achat.core.network.AnonymousRequest",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/network/ApiModels.kt:33:GoogleRequest",
            targetType = "yumo.achat.core.network.GoogleRequest",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/network/ApiModels.kt:37:RefreshRequest",
            targetType = "yumo.achat.core.network.RefreshRequest",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/network/ApiModels.kt:39:AuthResponse",
            targetType = "yumo.achat.core.network.AuthResponse",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/payment/LegacyPaymentRepository.kt:18:LegacyPaymentOrder",
            targetType = "yumo.achat.core.payment.LegacyPaymentOrder",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/payment/PaymentContract.kt:14:PaymentEnvelope",
            targetType = "yumo.achat.core.payment.PaymentEnvelope",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/payment/PaymentContract.kt:17:InitializePaymentRequest",
            targetType = "yumo.achat.core.payment.InitializePaymentRequest",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/payment/PaymentContract.kt:18:PaymentSdkParams",
            targetType = "yumo.achat.core.payment.PaymentSdkParams",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/payment/PaymentContract.kt:19:InitializedPayment",
            targetType = "yumo.achat.core.payment.InitializedPayment",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/payment/PaymentContract.kt:42:PaymentOrderStatus",
            targetType = "yumo.achat.core.payment.PaymentOrderStatus",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/payment/PaymentContract.kt:50:PaymentClientEvent",
            targetType = "yumo.achat.core.payment.PaymentClientEvent",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/payment/PaymentContract.kt:62:PaymentEventReceipt",
            targetType = "yumo.achat.core.payment.PaymentEventReceipt",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/payment/PaymentContract.kt:72:PaymentConfiguration",
            targetType = "yumo.achat.core.payment.PaymentConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/payment/PaymentEngine.kt:21:PaymentViewState",
            targetType = "yumo.achat.core.payment.PaymentViewState",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/payment/PaymentEventQueue.kt:17:QueuedPaymentEvent",
            targetType = "yumo.achat.core.payment.QueuedPaymentEvent",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/payment/PaymentStorage.kt:14:PaymentRecord",
            targetType = "yumo.achat.core.payment.PaymentRecord",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/payment/PurchaseFlow.kt:9:PurchaseFlowConfiguration",
            targetType = "yumo.achat.core.payment.PurchaseFlowConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/region/RegionAccess.kt:8:RegionAccessConfiguration",
            targetType = "yumo.achat.core.region.RegionAccessConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/region/RegionAccess.kt:13:LocalRegion",
            targetType = "yumo.achat.core.region.LocalRegion",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/visual/GenerationRequestRepository.kt:27:SourcePhoto",
            targetType = "yumo.achat.core.visual.SourcePhoto",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/visual/GenerationRequestRepository.kt:28:GenerationRequest",
            targetType = "yumo.achat.core.visual.GenerationRequest",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/visual/PrivateGenerationStorage.kt:19:GenerationConfiguration",
            targetType = "yumo.achat.core.visual.GenerationConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/visual/UploadedPhotoRepository.kt:15:UploadedPhoto",
            targetType = "yumo.achat.core.visual.UploadedPhoto",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/visual/VisualGenerationApi.kt:11:VisualCategory",
            targetType = "yumo.achat.core.visual.VisualCategory",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/visual/VisualGenerationApi.kt:12:VisualPage",
            targetType = "yumo.achat.core.visual.VisualPage",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/visual/VisualGenerationApi.kt:13:VisualTemplate",
            targetType = "yumo.achat.core.visual.VisualTemplate",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/visual/VisualGenerationApi.kt:21:VisualResult",
            targetType = "yumo.achat.core.visual.VisualResult",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/visual/VisualGenerationApi.kt:23:VisualTask",
            targetType = "yumo.achat.core.visual.VisualTask",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/visual/VisualGenerationApi.kt:31:VisualResource",
            targetType = "yumo.achat.core.visual.VisualResource",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/visual/VisualLibraryRepository.kt:8:VisualPollingConfiguration",
            targetType = "yumo.achat.core.visual.VisualPollingConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/wallet/CoinDisplayConfiguration.kt:6:CoinDisplayConfiguration",
            targetType = "yumo.achat.core.wallet.CoinDisplayConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/wallet/RechargeNotifications.kt:15:RechargeNotice",
            targetType = "yumo.achat.core.wallet.RechargeNotice",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/wallet/RechargeNotifications.kt:16:RechargeStreamConfiguration",
            targetType = "yumo.achat.core.wallet.RechargeStreamConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/wallet/WalletApi.kt:14:CoinProduct",
            targetType = "yumo.achat.core.wallet.CoinProduct",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/wallet/WalletApi.kt:31:ProductsResponse",
            targetType = "yumo.achat.core.wallet.ProductsResponse",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/wallet/WalletApi.kt:32:CurrencyResponse",
            targetType = "yumo.achat.core.wallet.CurrencyResponse",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/wallet/WalletApi.kt:35:CoinTransaction",
            targetType = "yumo.achat.core.wallet.CoinTransaction",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/wallet/WalletApi.kt:38:TransactionsResponse",
            targetType = "yumo.achat.core.wallet.TransactionsResponse",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/wallet/WalletApi.kt:40:CreateOrderRequest",
            targetType = "yumo.achat.core.wallet.CreateOrderRequest",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/wallet/WalletApi.kt:42:CreatedOrder",
            targetType = "yumo.achat.core.wallet.CreatedOrder",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/wallet/WalletApi.kt:55:WalletConfiguration",
            targetType = "yumo.achat.core.wallet.WalletConfiguration",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "core/src/main/java/com/zorv/core/wallet/WalletRepository.kt:14:WalletSnapshot",
            targetType = "yumo.achat.core.wallet.WalletSnapshot",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "integration/analytics-appsflyer/src/main/java/com/zorv/core/integration/appsflyer/AppsFlyerConfig.kt:3:AppsFlyerConfig",
            targetType = "yumo.achat.core.integration.appsflyer.AppsFlyerConfig",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "integration/analytics-appsflyer/src/main/java/com/zorv/core/integration/appsflyer/ForegroundAttributionStart.kt:32:AttributionStartStatus",
            targetType = "yumo.achat.core.integration.appsflyer.AttributionStartStatus",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        ),
        AchatModelExtensionDescriptor(
            sourceId = "integration/analytics-thinkingdata/src/main/java/com/zorv/core/integration/thinkingdata/ThinkingDataConfig.kt:5:ThinkingDataConfig",
            targetType = "yumo.achat.core.integration.thinkingdata.ThinkingDataConfig",
            fieldName = ACH_MODEL_TRACE_FIELD,
            serialName = ACH_MODEL_TRACE_SERIAL_NAME,
            legacyDefault = ACH_MODEL_TRACE_LEGACY_DEFAULT,
        )
    )
}
